---
title: "Figures"
author: "Jennie Lavine"
date: "8/11/2020"
output: html_document
---
```{r include=F}
knitr::opts_chunk$set(echo=F)
setwd('~/Dropbox/Antia-Lavine/Markdown/MainSimulations')
```

# Figure 2 code

This is the code for Fig 2a -- the MAPI data figure.
```{r Fig2A}
#######################
# Serosurvey data from http://www.biomedcentral.com/1471-2334/13/433
# Jennie Lavine
# June 10, 2020
######################
#setwd('/Users/jennielavine/Desktop/COVID-19')
require(tidyverse)

age_grps_min<-rep(c(0,1,4,7,15,31,41,51),8)
age_grps_max<-rep(c(1,4,7,15,31,41,51,100),8)
popsize<-rep(c(8,134,46,27,146,210,152,66),8)
serodat <- as.data.frame(cbind(age_grps_min,age_grps_max, popsize))
serodat$age_grps_mid<-(serodat$age_grps_max+serodat$age_grps_min)/2

Ig.names<-c('IgG','IgM')
serodat$Ig_class <- rep(c(rep(Ig.names[1],8),rep(Ig.names[2],8)),4)
s.names <- c('s229e','sOC43','sHKU1','sNL63')
serodat$strain <- rep(s.names,each=16)
serodat$pos<-NA
  
serodat$pos[serodat$strain=='s229e' & serodat$Ig_class=='IgG']<-
  c(2,94,41,24,130,178,135,61)

serodat$pos[serodat$strain=='sOC43' & serodat$Ig_class=='IgG']<-
  c(2,84,40,24,105,158,123,54)

serodat$pos[serodat$strain=='sHKU1' & serodat$Ig_class=='IgG']<-
  c(5,81,37, 22,113,155, 113,54)
 
serodat$pos[serodat$strain=='sNL63' & serodat$Ig_class=='IgG']<-
  c(4,78,35,18,95,150,113,56) 

serodat$pos[serodat$strain=='s229e' & serodat$Ig_class=='IgM']<-
  c(1,50,22,6,rep(0,4))

serodat$pos[serodat$strain=='sOC43' & serodat$Ig_class=='IgM']<-
  c(1,54,27,12, rep(0,4))

serodat$pos[serodat$strain=='sHKU1' & serodat$Ig_class=='IgM']<-
  c(3,71,25,11,rep(0,4))

serodat$pos[serodat$strain=='sNL63' & serodat$Ig_class=='IgM']<-
  c(1,55,27,14, rep(0,4))

z=1.96 

serodat$prev <- serodat$pos/serodat$popsize
serodat$err <-  z*sqrt((serodat$prev*(1-serodat$prev))/
                         serodat$popsize)
serodat$err.min<-serodat$prev-serodat$err
serodat$err.min[which(serodat$err.min<0)]<-0
serodat$err.max<-serodat$prev+serodat$err
serodat$err.max[which(serodat$err.max>1)]<-1

cols_bars<-c("#b2d4ac","#D08CC6")
col_err<-c("#485a2e", "#674E81")

age.widths<-serodat$age_grps_max[1:8] - serodat$age_grps_min[1:8]
g <- ggplot(data=serodat, aes(y=prev, x=age_grps_mid))
g+ geom_point(aes(colour=Ig_class)) + 
  geom_line(aes(colour=Ig_class),linetype='dashed')+
  scale_fill_manual(values=cols_bars)+
  scale_colour_manual(values=col_err)+
  geom_errorbar(aes(ymin = err.min, ymax = err.max, colour=Ig_class), width = .25)+
  facet_wrap(vars(strain)) 


rawdat <- sapply(s.names,function(x) NULL)
age_inds<-unique(serodat$age_grps_mid)
for (i in 1:length(s.names)){
  temp<-subset(serodat, Ig_class=='IgM' & strain==s.names[i])
  for(j in 1:length(age_inds)){
    temp2<-subset(temp, age_inds==age_inds[j])
    rawdat[[s.names[i]]]<-c(rawdat[[s.names[i]]],
                            rep(age_inds[j], temp2$pos))
    }
  }

means <- lapply(rawdat, mean)
sds <- lapply(rawdat, function(x){
  sqrt(var(x)/length(x))})

ests<-rbind(as.data.frame(means), as.data.frame(sds))
rownames(ests)<-c('means','sds')
ests['ci_low',]<-apply(ests, 2, function(x){
  x['means']-1.96*x['sds']
})

ests['ci_hi',]<-apply(ests, 2, function(x){
  x['means']+1.96*x['sds']
})
```



This is the code for the steady state simulations (Fig 2b and Supp Figs).  I don't run it here becuase it takes a long time to run.

```{r Fig2b1, eval=F}
require(rootSolve)
require(deSolve)
require(tidyverse)

covid_fun <- function(t, state, parameters) { 
  
  with(as.list(c(state, parameters)),{
    dS <- mu*(sum(S,I1, R1, R2, I2)) - beta0*(1+beta1*cos(2*pi*t))*S*sum(I1, I2*rel_2inf) - mu*S
    dI1 <- beta0*(1+beta1*cos(2*pi*t))*S*sum(I1, I2*rel_2inf) - (gammaR + mu) * I1
    dR1 <- gammaR*I1 + gammaR*gamma_mod*I2 - (mu+omega1)*R1
    dR2 <- omega1*R1 - beta0*(1+beta1*cos(2*pi*t))*R2*sum(I1,I2*rel_2inf) - mu*R2
    dI2<- beta0*(1+beta1*cos(2*pi*t))*R2*sum(I1,I2*rel_2inf) - (gammaR*gamma_mod+mu)*I2
    
    list(c(dS, dI1, dR1, dR2, dI2))
  }) 
}

# initial conditions
y<- c(
  S = 0.2, 
  I1 = 0.0001, 
  R1 = 0.3, 
  R2 = 0.3, 
  I2 = 0.001
)
y/sum(y)

state_init<-y

gammaR <- 365/9
mu<-1/50
R0 <- 2
beta0 <- R0*(gammaR+mu)
omega1 <- seq(0,2,by=0.01)
rel_2inf<- seq(0,1,by=0.01)
gamma_mod <- c(1)
beta1 <- 0 #seasonal forcing parameter


param_grid<-expand.grid(beta0=beta0, gammaR=gammaR, omega1=omega1, rel_2inf=rel_2inf, gamma_mod=gamma_mod, mu=mu, beta1=beta1)


times <- seq(0, 100, by = 0.01)

# direct iteration  - enforces  positivity..
res<-list(NULL)
i=1
out<-ode(y = state_init, times = times, 
         func = covid_fun, parms = param_grid[i,])
y=apply(tail(out, 100), 2, mean)[-1]
ST <- stode(y = y, func = covid_fun, parms = param_grid[i,], pos = TRUE)
res[[i]]<-ST
param_grid$ST_S[i]<-ST$y['S']
param_grid$ST_I1[i]<-ST$y['I1']
param_grid$ST_R1[i]<-ST$y['R1']
param_grid$ST_R2[i]<-ST$y['R2']
param_grid$ST_I2[i]<-ST$y['I2']
param_grid$steady[i]<-attr(ST, 'steady')

for (i in 2:nrow(param_grid)){
  out<-ode(y = state_init, times = times, 
      func = covid_fun, parms = param_grid[i,])
  y=apply(tail(out, 100), 2, mean)[-1]
  ST <- stode(y = y, func = covid_fun, parms = param_grid[i,], pos = TRUE)
  res[[i]]<-ST
  param_grid$ST_S[i]<-ST$y['S']
  param_grid$ST_I1[i]<-ST$y['I1']
  param_grid$ST_R1[i]<-ST$y['R1']
  param_grid$ST_R2[i]<-ST$y['R2']
  param_grid$ST_I2[i]<-ST$y['I2']
  param_grid$steady[i]<-attr(ST, 'steady')
  print(i)
}

param_grid$mapi<-1/(param_grid$beta0*(
  param_grid$ST_I1+param_grid$rel_2inf*param_grid$ST_I2))

#write_csv(param_grid, 'output_0615_R02.csv')
```


Next we plot from three .csv files that were made running the above code with three different values of R0.

```{r Fig2b2}
require(tidyverse)
library(readr)

res10<-read_csv('steady_state_res/output_0615_R010.csv')
res10$R0<-10
res5<-read_csv('steady_state_res/output_0614_R05.csv')
res5$R0<-5
res2 <-read_csv('steady_state_res/output_0615_R02.csv')
res2$R0<-2
res<-rbind(res10,res2, res5)

####Calculate contribution of secondary cases to FOI on S
rel_cont_I2<-expression(rel_2inf*ST_I2/(ST_I1+rel_2inf*ST_I2))
res$foi_I2_prop<-eval(rel_cont_I2, res)

res$age_lev<-cut(res$mapi, c(0,1,2,3.4,5.1,7,10,100))
temp<-subset(res, age_lev=="(3.4,5.1]" & res$omega1>=0.5)
range(temp$rel_2inf)
range(temp$foi_I2_prop)

g<-ggplot(data=subset(res, R0==5), aes(x=rel_2inf, y=omega1))
g + geom_raster(aes(fill=age_lev))+
  scale_fill_brewer(palette = "PuOr") +
  labs(x=expression(rho), y=expression(omega), fill='age grp (yr)')

#+ facet_grid(vars(R0))
```

# Figure 4
Code for Figure 4

```{r Fig4a}
################
#SARS & MERS projections
# Jennie Lavine
# Aug 6, 2020
################

#setwd('/Users/jennielavine/Desktop/COVID-19')
library(deSolve) 
#require(msm)
require(tidyverse)
#require(GGally)
library(dplyr)
library(ggplot2)
library(reshape2)

require(tidyverse)

dat<-data.frame(cbind(age.grp=NA, CFR=NA))

cfr.age<-data.frame(
  path=rep(c('mers', 'sars','covid'),each=9),
  age=rep(as.character(unique(cut(1:104, 
                                  breaks=c(0,10,20,30,40,50,60,70,80,105)))), 3)
)


cfr.age$tot[cfr.age$path=='mers']<-c(8, 27, 314, 215, 264, 321,333,214, 93)
cfr.age$death[cfr.age$path=='mers']=c(5, 8, 52,63, 76, 103, 114, 118, 49)

cfr.age$tot[cfr.age$path=='covid']<-c(
  416, 549, 3619, 7600, 8571, 10008, 8583, 3918, 1408)
cfr.age$death[cfr.age$path=='covid']<-c(
  0,1,7,18,38, 130,309, 312, 208)

cfr.age$cfr<-cfr.age$death/cfr.age$tot

cfr.age$cfr[cfr.age$path=='sars']<-c(0,0,0.9,3.0, 5.0, 10,17.6, 28, 26.3)/100

cfr.age$cfr.lo<-cfr.age$cfr-
  1.96*sqrt(cfr.age$cfr*(1-cfr.age$cfr)/cfr.age$tot)
cfr.age$cfr.hi<-cfr.age$cfr+
  1.96*sqrt(cfr.age$cfr*(1-cfr.age$cfr)/cfr.age$tot)

#View(cfr.age)

g <- ggplot(data=cfr.age, aes(x=age, y=cfr))
g+geom_point(aes(colour=path))+
  geom_errorbar(aes(ymin = cfr.lo, ymax = cfr.hi, colour=path), width = .25)


```

```{r Fig4b}


MODEL <- function(times, logstate, parameters) {
  state=exp(logstate)
  with(as.list(c(state, parameters)), {
    S = matrix(state[1:J], nrow = J, ncol=1)
    I1 = matrix(state[(J+1):(2*J)], nrow = J, ncol=1)
    R1 = matrix(state[(2*J+1):(3*J)], nrow = J, ncol=1)
    R2 = matrix(state[(3*J+1):(4*J)], nrow = J, ncol=1)
    I2 = matrix(state[(4*J+1):(5*J)], nrow = J, ncol=1)
    
    N = sum(state)
    beta =beta0*(1+beta1*cos(2*pi*times+(pi/3)))
    lambda.in <- matrix(c(0, lambda), nrow=J, ncol=1)
    lambda.out <- matrix(c(lambda, 0), nrow=J, ncol=1)

    dS <- mu*N + 
      lambda.in * S - 
      beta * S * sum(I1+I2*rho) - 
      (delta + lambda.out)*S
    dI1 <- lambda.in * I1 + 
      beta * S * sum(I1+I2*rho) - 
      (delta + lambda.out + gamma) * I1
    dR1 <- lambda.in * R1 + 
      gamma * (I1 + I2) - 
      (delta + omega + lambda.out) * R1
    dR2 <- lambda.in * R2 + 
      omega * R1 -
      beta * R2 * sum(I1+I2*rho) - 
      (delta + lambda.out) * R2
    dI2 <- lambda.in * I2 + 
      beta * R2 * sum(I1+I2*rho) - 
      (gamma + delta + lambda.out) * I2
    
    return(list(c(dS, dI1, dR1, dR2, dI2)/state))
  })
}


fun_0.5yr <- function(deaths = x, cases = y, ind) {
  sum(deaths[ind:(ind + round(steps.yr/2))]) / sum(cases[ind:(ind + round(steps.yr/2))])
}
########################
#Age data, hospitalization rates and CFRs
# Age distribution of US from https://www.census.gov/prod/cen2010/briefs/c2010br-03.pdf
# Case Fatality rates from https://www.cdc.gov/coronavirus/2019-ncov/hcp/planning-scenarios.html
#age-specific death rates from https://www.cdc.gov/nchs/data/databriefs/db355_tables-508.pdf#page=3 2018 data
#birth rate from https://www.cdc.gov/nchs/fastats/births.htm
#########################

age_dist<-read.csv('US_age_dist.csv')[,1:2]
colnames(age_dist) <- c('age', 'pop.size')
#age_dist$prop<-age_dist$pop.size/sum(age_dist$pop.size)

age_9grp <- as.data.frame(cbind('age'=c(seq(10,80, by=10), 105) , 
                                'pop.size'=c(sum(age_dist$pop.size[1:2]), 
                                             sum(age_dist$pop.size[3:4]), 
                                             sum(age_dist$pop.size[5:6]), 
                                             sum(age_dist$pop.size[7:8]), 
                                             sum(age_dist$pop.size[9:10]), 
                                             sum(age_dist$pop.size[11:12]), 
                                             sum(age_dist$pop.size[13:14]), 
                                             sum(age_dist$pop.size[15:16]), 
                                             sum(age_dist$pop.size[17:21])
                                )))

age_9grp$prop <- age_9grp$pop.size/sum(age_9grp$pop.size)

age_9grp$cfr.sars <- cfr.age$cfr[cfr.age$path=='sars']
age_9grp$cfr.covid <- cfr.age$cfr[cfr.age$path=='covid']
age_9grp$cfr.mers <- cfr.age$cfr[cfr.age$path=='mers']
tot_pop <- sum(age_9grp$pop.size)


death_rate_age<-as.data.frame(cbind(age=seq(25,95,by=10), 
                                    number=c(30154,58844,80380,164837,374836,543778,675205,880280),
                                    rate=c(70.2,128.8,194.7,395.9,886.7,1783.3,4386.1,13450.7)/100000))

death_rate.glm<-with(
  death_rate_age,glm(rate ~ age,
                     family=gaussian(link='log'))
)

pred_death_rate<-exp(predict(death_rate.glm, data.frame(age=seq(0,100,by=0.5))))

mod.pred<-round(exp(predict(death_rate.glm, data.frame(age=c(seq(5,75,by=10),90) ))),5)
mean_death_rate<-sum(age_9grp$prop*mod.pred)
age_9grp$br.death<-mod.pred

#Total number of births in 2018 in the US: 3791712
#Total number of deaths in 2018 in the US: 2813503
birth.rate<-11.6/1000



##################
#Set initial conditions
##################

J=9
state.names<-paste(rep(c('S','I1','R1','R2','I2'),each=J),
                   rep(letters[1:J], 5),sep='')
state_init <- rep(1E-15, 5*J)
names(state_init)<-state.names
state_init[grep('S',state.names)]<-age_9grp$prop
state_init[grep('I1', state.names)]<-1/sum(age_9grp$pop.size)
state_init<-log(state_init/sum(state_init))

param_grid<-expand.grid(
  R0 = c(2,4,6), 
  beta1 = 0.2, #seasonal forcing parameter
  gamma = 365/9, 
  omega = 1,
  rho = 0.7,
  disease = c('covid','sars','mers')
)

params<-list(NULL)
for(i in 1:nrow(param_grid)){
  params[[i]]<- list(
    mu = matrix(c(birth.rate, rep(0, (J-1))), nrow=J, ncol=1),
    delta = matrix(age_9grp$br.death, nrow=J, ncol=1),
    beta0 = (365/9 + birth.rate)*param_grid$R0[i], 
    beta1 = 0.2, #seasonal forcing parameter
    lambda = matrix(1/(diff(age_9grp$age)),nrow=(J-1), ncol=1),
    gamma = 365/9, 
    omega = 1,
    rho = 0.7,
    R0=param_grid$R0[i],
    disease = param_grid$disease[i],
    cfr = age_9grp[,grep(param_grid$disease[i],names(age_9grp))]
  )
}

steps.yr = 365
maxt = 10
times=seq(0,maxt, by=1/steps.yr)
sim.n<-nrow(param_grid)

cases_res<-matrix(rep(NA, sim.n*steps.yr*maxt), ncol=sim.n)
cfr_res<-matrix(rep(NA, sim.n*(steps.yr*maxt-(round(steps.yr/2)+1))), ncol=sim.n)
infecs_res<-list(NULL)

for(j in 1:length(params)){
  out <- ode(y=state_init, times=times, func=MODEL, parms=params[[j]])
  out<-exp(out)
  out[,1]<-log(out[,1])

  probs.step <- 1-pexp(rate=unlist(params[[j]]['gamma']), 1/steps.yr)
  
  I_t1 <- tail(out[, grep('I1',colnames(out))], -1)
  I_t0 <- head(out[, grep('I1',colnames(out))], -1)
  X = I_t1 - (I_t0 * probs.step)  #calculate X, new infections at time t
  ##I_t1 = I_t0*P(staying in I in time step) + X
  ##X = I_t1 - I_t0*P(staying in I in time step)
  
  newI_step<-X*tot_pop
  
  deaths <- t(t(newI_step) * params[[j]]$cfr)
  deaths_tot <- apply(deaths, 1, sum)
  cases_tot <- apply(newI_step, 1, sum)
  
  cfr_0.5yr <- c(NULL)
  for (i in 1:(length(deaths_tot) - round(steps.yr/2)-1)) {
    cfr_0.5yr[i] <- fun_0.5yr(deaths = deaths_tot,
                              cases = cases_tot,
                              ind = i)
  }

  infecs_res[[j]] <- newI_step
  cases_res[, j] <- cases_tot
  cfr_res[, j] <- cfr_0.5yr
  print(j)
}



#################
#Plotting
###############
##Plot CFR
cfr_res<-as.data.frame(cfr_res)
names(cfr_res)<-paste( param_grid[,'disease'],' R0=',param_grid[,'R0'],  sep='')
cfr_res$time<-tail(times, nrow(cfr_res))
cfr_clean<-gather(cfr_res, params, cfr, -time)
cfr_clean$disease <- unlist(str_split(cfr_clean$params, ' '))[1:2==1]
cfr_clean$R0 <- unlist(str_split(cfr_clean$params, ' '))[1:2==2]
cfr_clean$disease2<-factor(cfr_clean$disease, levels=c('covid','sars','mers'))

cfr.plot <- ggplot(data=cfr_clean, aes(x=time, y=cfr))

cfr.plot + geom_line(aes(col=R0)) + 
  facet_grid(rows=vars(disease2), scales='free')
```

# Fig 3

```{r Fig3a}

#Plot Cases & Ages
annotation_custom2 <- function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn,
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}


temp <- as.data.frame(infecs_res[[1]])
temp$R0<-params[[1]]$R0
temp$disease<-params[[1]]$disease
temp$time<-times[-1]
age.data<-temp
for(i in 2:length(infecs_res)){
  temp <- as.data.frame(infecs_res[[i]])
  temp$R0<-params[[i]]$R0
  temp$disease<-params[[i]]$disease
  temp$time<-times[-1]
  age.data<-rbind(age.data, temp)
}               


age.data$tot_cases <- apply(age.data[,1:J], 1, sum)
props<-age.data[,1:J]/age.data$tot_cases
colnames(props)<-paste(colnames(props), '.prop', sep='')
age.data<-cbind(age.data, props)

age.data<-age.data%>% 
  pivot_longer(grep('.prop',colnames(age.data)), 
               names_to = "age_grp", values_to = "prop_cases")

# Plot
R0.labs<-paste('R0', '=', c(2,4,6), sep='')
names(R0.labs)<-c(2,4,6)
age.labs<-c(paste( c(0,head(age_9grp$age,-2)),'-',
                head(age_9grp$age,-1), ' yr', sep=''),
            paste('>',age_9grp$age[8], ' yr', sep='')
 )

g<- ggplot(subset(age.data, disease=='sars'), aes(x=time))

dat_text <- data.frame(
  label = R0.labs,
  R0   = c(2,4,6),
  x     = rep(2,3),
  y     = rep(2.5E7,3)
)

max.y<-max(age.data$prop_cases*max(age.data$tot_cases))

g.main <- g + geom_area(aes(y=prop_cases*max(tot_cases), fill=age_grp), alpha=0.8 , size=1) + 
  scale_fill_discrete(labels = age.labs)+
  geom_line(aes(y=tot_cases) ) +
  scale_y_continuous(limits=c(0,max.y+(max.y/100)), 
    sec.axis = sec_axis( trans=~./max.y, 
        name="Prop in age grp (colored area)", breaks=c(0,1))) +
  facet_grid(vars(R0)) +
  labs(x='Time (yr)', y='Daily cases (----)', 
       fill='Proportion of \ninfections by \n age group') + 
  geom_text(data = dat_text,
            mapping = aes(x = x, y = y, label = label)) +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank())

g.tail.2 <- ggplot(data = subset(age.data, time>5 & R0==2), aes(x=time)) + 
  geom_line(aes(y=tot_cases), size=0.25) +  
  guides(fill=FALSE) +
  scale_x_continuous(breaks=c(5,10)) +
  scale_y_continuous(breaks = c(0,100000), limits=c(0,100000), labels=c(0,1E5))+
  theme_bw(base_size=8) +  ## makes everything smaller
  theme(panel.background = element_rect(fill="white"),  ## white plot background 
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=rel(0.7)), ## tiny axis text
        axis.text.y = element_text(size=rel(0.7)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank()) 

g.tail.4 <- ggplot(data = subset(age.data, time>5 & R0==4), aes(x=time)) + 
  geom_line(aes(y=tot_cases), size=0.25) +  
  guides(fill=FALSE) +
  scale_x_continuous(breaks=c(5,10)) +
  scale_y_continuous(breaks = c(0,100000), limits=c(0,100000), labels=c(0,1E5))+
  theme_bw(base_size=8) +  ## makes everything smaller
  theme(panel.background = element_rect(fill="white"),  ## white plot background 
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=rel(0.7)), ## tiny axis text
        axis.text.y = element_text(size=rel(0.7)), ## tiny axis text

        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank())


g.tail.6 <- ggplot(data = subset(age.data, time>5 & R0==6), aes(x=time)) + 
  geom_line(aes(y=tot_cases), size=0.25) +  
  guides(fill=FALSE) +
  scale_x_continuous(breaks=c(5,10)) +
  scale_y_continuous(breaks = c(0,100000), limits=c(0,100000), labels=c(0,1E5))+
  theme_bw(base_size=8) +  ## makes everything smaller
  theme(panel.background = element_rect(fill="white"),  ## white plot background 
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size=rel(0.7)), ## tiny axis text
        axis.text.y = element_text(size=rel(0.7)), ## tiny axis text

        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank())

g.main + annotation_custom2(grob=ggplotGrob(g.tail.2), 
                            data=subset(age.data, R0==2),
                            ymin = 1.3E7, ymax=3.5E7, xmin=5, xmax=10) +
  annotation_custom2(grob=ggplotGrob(g.tail.4), 
                     data=subset(age.data, R0==4),
                     ymin = 1.3E7, ymax=3.5E7, xmin=5, xmax=10)+
  annotation_custom2(grob=ggplotGrob(g.tail.6), 
                     data=subset(age.data, R0==6),
                     ymin = 1.3E7, ymax=3.5E7, xmin=5, xmax=10)


```


Fig 3b

```{r Fig3b1, eval=F}
param_grid<-expand.grid(
  R0 = seq(1.05,6,length=25), 
  beta1 = 0.2, #seasonal forcing parameter
  gamma = 365/9, 
  omega = seq(0.1, 2, length=25),
  rho = c(0.05, 0.35, 0.7, 1),
  disease = c('covid')
)

params<-list(NULL)
for(i in 1:nrow(param_grid)){
  params[[i]]<- list(
    mu = matrix(c(birth.rate, rep(0, (J-1))), nrow=J, ncol=1),
    delta = matrix(age_9grp$br.death, nrow=J, ncol=1),
    beta0 = (365/9 + birth.rate)*param_grid$R0[i], 
    beta1 = param_grid$beta1[i], #seasonal forcing parameter
    lambda = matrix(1/(diff(age_9grp$age)),nrow=(J-1), ncol=1),
    gamma = param_grid$gamma[i], 
    omega = param_grid$omega[i],
    rho = param_grid$rho[i],
    R0=param_grid$R0[i],
    disease = param_grid$disease[i],
    cfr = age_9grp[,grep(param_grid$disease[i],names(age_9grp))]
  )
}

#when does the overall CFR drop below 0.001?
cfr_thresh=0.001
param_grid$CFR_lo_time <- NA
#when do cumulative cases exceed 50% of initial population size?
cumcases_thresh <- 0.75
param_grid$cumcases_hi_time <- NA
#how many COVID-induced deaths have occurred 1-yr into pandemic?
param_grid$cumdeaths_1yr <- NA

#

###
maxt=30
steps.yr=365
times <- seq(0, maxt, by = 1/steps.yr)

fun_0.5yr <- function(deaths = x, cases = y, ind) {
  sum(deaths[ind:(ind + round(steps.yr/2))]) / sum(cases[ind:(ind + round(steps.yr/2))])
}

tic()
for(j in 1:nrow(param_grid)) {
  out <- ode(y=state_init, times=times, func=MODEL, parms=params[[j]])
  out<-exp(out)
  out[,1]<-log(out[,1])
  
  probs.step <- 1-pexp(rate=unlist(params[[j]]['gamma']), 1/steps.yr)
  
  I_t1 <- tail(out[, grep('I1',colnames(out))], -1)
  I_t0 <- head(out[, grep('I1',colnames(out))], -1)
  X = I_t1 - (I_t0 * probs.step)  #calculate X, new infections at time t
  ##I_t1 = I_t0*P(staying in I in time step) + X
  ##X = I_t1 - I_t0*P(staying in I in time step)
  
  newI_step<-X*tot_pop
  
  deaths <- t(t(newI_step) * params[[j]]$cfr)
  deaths_tot <- apply(deaths, 1, sum)
  cases_tot <- apply(newI_step, 1, sum)
  cumcases_tot <- cumsum(cases_tot)
  cumdeath_tot<- cumsum(deaths_tot)
  
  cfr_0.5yr <- c(NULL)
  for (i in 1:(length(deaths_tot) - round(steps.yr/2)-1)) {
    cfr_0.5yr[i] <- fun_0.5yr(deaths = deaths_tot,
                              cases = cases_tot,
                              ind = i)
  }

param_grid$CFR_lo_time[j] <- min(which(cfr_0.5yr < cfr_thresh)) / steps.yr
param_grid$cumcases_hi_time[j] <- 
  min(which(cumcases_tot > (tot_pop * cumcases_thresh))) / steps.yr

param_grid$cumdeaths_1yr[j] <- cumdeath_tot[steps.yr]

print(j)

}
toc()

#write_csv(param_grid, 'sensitivity_0809.csv')
```

Plots based on csv from above code
```{r Fig3b2}
res<-read_csv('sensitivity_0809.csv')
#res<-subset(res, rho==0.7)

g <- ggplot(data=subset(res, rho=0.7), aes(x=R0, y=omega))

g + geom_tile(aes(fill=CFR_lo_time)) + 
  scale_fill_gradient2(trans = "log", 
          breaks = c(0.5,2,8, 32), midpoint=log(0.5))+
  labs(x=expression("R"[0]), y=expression(omega), 
       fill='yrs to \nCFR=0.001')


```

